$ANSIBLE_VAULT;1.1;AES256
36633565366132643563333835386536633133303432313334333334656665316239343962383534
3939306665346637313131343230346262343865313938640a376365643239323234366335376463
39333438623839323239386435663162663163636361623430326430366661643035633530306338
3861623332386531660a333361623937666161306330626561336539373565363435313830366162
61356332633533633863313732633537303064316464393161326432306239313030363163323866
64326239356639376530316166303437396564383261663335616133393837303361626364363731
64666431373333376462663434323531363036356466313265316666616539626532373166383966
33666338613461636238666364393662663336653763313737383437353765343961383466646166
39656436343135646135653337306335323038333162366234633434373564643439616131636338
35623836373837356339313665666635383430346561353762623938643733356236623533376264
63363733316562396138363530303835633136343433366539393336643631633162316433353835
65623635356337363938623635353461353463636238643335366663343230313939373137303235
62383730643030353539386536393136346166303264383637663131396661623739613663373838
66326361636561306431343938623465393330653937616632393034316664333261613132616231
32646331343631303739373234373139386163643532396435346163386139343833656264626434
36313935643764303663663264383466313536666638356130363265633962666236363065336464
66633338376264656334613235326431643439633535666266313464623432383838
